### PR TITLE
edit description, devs and urls in `meta.yaml`, fix sha256

### PR DESCRIPTION
**Pull request by danielhuppmann**

### CODE REVIEW

**Comment by danielhuppmann** [comment]
@gidden, it seems that the sha256 was not correctly set in the PR by the bot. I tried to replace it manually with the one from pypi, but that refers to the wheel, not the tar.gz, so that doesn't work either. Any ideas?

**Comment by gidden** [comment]
hey @danielhuppmann here we also need to bump the build number in the recipe, since we already have a 0.3.0 release

**Comment by danielhuppmann** [comment]
it already says `{% set version = "0.3.0" %}` in line 1 of `meta.yaml` - what else needs to be changed?

**Comment by gidden** [comment]
should be a line like "build: 0". This needs to be bumped to 1 if we are
not changing the version number. That will make the package version on
conda look like 0.3.0-1 to identify it as a conda package change and not a
library change.

**Comment by danielhuppmann** [comment]
but there is no version 0.3.0 on conda, because the build was never successful

**Comment by gidden** [comment]
Very true! My mistake!

**Comment by gidden** [comment]
Ok, before we merge, can you remove the geo deps? That would be

```
    - geopandas
    - cartopy
    - gdal
    - fiona
```

**Comment by gidden** [comment]
Speaking of, we should probably at some point move to the model of having our unit tests installed (or some minimal functional testing) with the library. That way we can actually test things here as well.

**Comment by danielhuppmann** [comment]
Removed the deprecated dependencies.

Regarding the unit testing, agree, but can we tackle this with a release `>0.3.0`?

**Comment by gidden** [comment]
Yup! Maybe make an issue on pyam for it, though?

**Comment by danielhuppmann** [comment]
created an issue and assigned you, @gidden ;-)

is this PR good to go, so that we can finalise release 0.3.0?

**Comment by gidden** [comment]
thanks @danielhuppmann, welcome to the maintainer team =)

**Pull request merged**
